#!/usr/bin/env bash

VOID="\033[0m"
BLUE="\033[0;34m"
RED="\033[38;5;1m"

echo -e "           $RED                                    :e       					         "
echo "                                              'M$\\              		             	     "
echo "                                              sf\$\$br          					         "
echo "                                            J\\J\\J\$L\$L        				             "
echo "                                          :d  )fM\$\$\$\$\$r                             "
echo "                                       ..P*\ .4MJP   '*\\                                     "
echo "                              sed\"\"\"\"\"\" ser d\$\$\$F                                 "
echo "                         .M\  ..JM\$\$\$B\$\$\$\$BJ\$MR  ...                          "
echo "                       dF  nMMM\$\$\$R\$\$\$\$\$\$\$h\"\$ks\$\$\"\$\$r         "
echo "                     J\\.. .MMM8\$\$\$\$\$LM\$P\\..'**\\    *\\                         "
echo "                    d :d\$r \"M\$\$\$\$br'\$M\\d\$R                                    "
echo "                   J\\MM\\ *L   *M\$B8MM\$B.**                                              "
echo "                  :fd\$>  :fhr 'MRM\$\$M\$\$\"                                           "
echo "                 4M\$P .\$\$*.J*\$\$**                                                   "
echo "                 M4\$> '\$>dRdF                                                             "
echo "                 MMM\\   *L*B.         KANGOUROUGE                                            "
echo "                :\$\$F     ?k\"Re                                                           "
echo "              .\$\$P\\        **'\$\$B...                                                 "
echo "           :e\$F\"               '\"\"\"\"                                                   "
echo
echo -e "$BLUE                      Art by Rosemary Lyndall Wemm      $VOID                     "
